public class Constants {

    public static final String PRIORITY_FIELD = 'Priority__c';

    public static final String WAITING = 'Waiting';

    public static final String OCCUPIED = 'Occupied';

    public static final String WAITING_FOR_BED = 'Waiting For Bed';

    public static final String AVAILABLE = 'Available';

    public static final String ADMITTED = 'Admitted';

    public static final String HIGH = 'High';
}